apiVersion: pipelinesascode.tekton.dev/v1alpha1
kind: Repository
metadata:
  annotations:
    build.appstudio.openshift.io/application: test-app-167084251
    build.appstudio.openshift.io/build: "true"
    build.appstudio.openshift.io/component: python
    build.appstudio.openshift.io/type: build
    build.appstudio.openshift.io/version: "0.1"
    pipelines.appstudio.openshift.io/type: build
  creationTimestamp: null
  name: python
  namespace: zsv69g1w
spec:
  git_provider:
    secret:
      key: github.token
      name: pipelines-as-code-secret
    webhook_secret:
      key: https___github.com_hac-test_private-repo-check
      name: pipelines-as-code-webhooks-secret
  url: https://github.com/hac-test/private-repo-check
